/** Plain-English names. Short form only in the hover, never as the main label. */
export type GlossaryEntry = { name: string; short?: string; hint: string };

export const GLOSSARY: Record<string, GlossaryEntry> = {
  command: {
    name: "Home",
    short: "Command",
    hint: "The first screen after login. It shows what needs a decision today.",
  },
  approvals: {
    name: "Approvals",
    short: "Waiting for a yes",
    hint: "A boss must say yes or no before money is spent or a paper is released.",
  },
  "owners hub": {
    name: "Open items",
    hint: "Things still waiting on this seat: yes/no, papers, failed work.",
  },
  capital: {
    name: "Company money",
    hint: "How much money is planned and already spent. Land that is only an idea is not counted as spent.",
  },
  "change control": {
    name: "Site questions and quality",
    short: "Change control",
    hint: "Three kinds of site paper: a question to design, work that failed inspection, and extra paid work.",
  },
  rfi: {
    name: "Question to design",
    short: "RFI",
    hint: "The site team asks the drawing team a question. Work waits until they answer.",
  },
  ncr: {
    name: "Failed work report",
    short: "NCR",
    hint: "Inspection found work that is not as per drawing or quality. Fix it, then inspect again.",
  },
  change: {
    name: "Paid extra work",
    short: "VO",
    hint: "Extra or changed work that costs money. A boss must approve it before it is done.",
  },
  vo: {
    name: "Paid extra work",
    short: "VO",
    hint: "Variation order — extra or changed work that costs money. A boss must approve it.",
  },
  oc: {
    name: "Permission to live in the building",
    short: "OC / CC",
    hint: "Occupation / completion certificate from the authority. Keys cannot be given before this.",
  },
  cc: {
    name: "Completion certificate",
    short: "CC",
    hint: "The authority says the building is complete. Often needed with the occupation certificate.",
  },
  dlp: {
    name: "Defect period after handover",
    short: "DLP",
    hint: "Months after the buyer gets keys when you still fix defects for free.",
  },
  snag: {
    name: "Defect to fix",
    hint: "A small fault in the flat (leak, paint, door) that must be closed before keys.",
  },
  snags: {
    name: "Defects to fix",
    hint: "Faults in the flat that must be closed before keys are given.",
  },
  po: {
    name: "Purchase order",
    short: "PO",
    hint: "A written order to a vendor to supply or do work at an agreed price.",
  },
  rfq: {
    name: "Ask vendors for prices",
    short: "RFQ",
    hint: "You send the same work list to vendors and compare their prices before ordering.",
  },
  ra: {
    name: "Contractor running bill",
    short: "RA bill",
    hint: "A bill for work already done on site. Finance checks it against the order.",
  },
  grn: {
    name: "Goods received note",
    short: "GRN",
    hint: "Paper that says material actually arrived on site. This desk only counts quantity, not that paper.",
  },
  kyc: {
    name: "Identity check",
    short: "KYC",
    hint: "PAN, Aadhaar or company papers that prove who the person or vendor is.",
  },
  gstin: {
    name: "GST number",
    short: "GSTIN",
    hint: "The tax number of a company. Needed before a vendor can be fully approved.",
  },
  emi: {
    name: "Loan instalment",
    short: "EMI",
    hint: "Monthly loan payment. Here it is only a reminder — the real books stay in ERPNext.",
  },
  clu: {
    name: "Land use conversion",
    short: "CLU",
    hint: "Permission to use farm or other land for a housing project.",
  },
  bocw: {
    name: "Labour welfare tax return",
    short: "BOCW",
    hint: "A government return and cess for construction workers. File it on time.",
  },
  rera: {
    name: "RERA filing",
    hint: "Housing regulator filing. Buyers and the government can see project progress.",
  },
  identified: {
    name: "Not yet owned",
    short: "Identified",
    hint: "The khasra is on the list. You do not own it until title checks are clear and acquisition is complete.",
  },
  tally: {
    name: "Company accounts",
    short: "ERPNext",
    hint: "The official books, in ERPNext at D:\\ERPNext. Atlas never types a voucher unless posting is explicitly turned on. We only match and flag mismatches.",
  },
  erpnext: {
    name: "Company accounts",
    short: "ERPNext",
    hint: "The official books. Sibling system at D:\\ERPNext. Atlas talks to it by API only.",
  },
  crm: {
    name: "Sales partners",
    short: "CRM",
    hint: "Outside agencies and their commission. Buyer follow-up happens on Buyer leads.",
  },
  wbs: {
    name: "Cost code",
    short: "WBS",
    hint: "A number that says which part of the building this money belongs to.",
  },
  bim: {
    name: "Drawing quantity",
    short: "BIM",
    hint: "How much material the drawings say you need, to compare with site measure.",
  },
  sla: {
    name: "Time limit to reply",
    short: "SLA",
    hint: "Hours left to answer. Demo clock only on this host.",
  },
  hold: {
    name: "Hold on a unit",
    hint: "The flat is locked for one buyer for a few days so nobody else can sell it.",
  },
  pipeline: {
    name: "Buyer leads",
    hint: "People who showed interest, from first call to booking.",
  },
  inbound: {
    name: "Incoming leads",
    hint: "Leads that arrived from portals or email. Not live websites yet.",
  },
  "customer 360": {
    name: "Buyer file",
    hint: "One place for the buyer’s phone, unit, visits and messages.",
  },
  controls: {
    name: "Materials and quantities",
    hint: "What came in, what went to site, and whether site measure matches the drawing.",
  },
  commercial: {
    name: "Vendors and orders",
    hint: "Invite vendors, compare prices, and raise a purchase order.",
  },
  quotations: {
    name: "Price quotes",
    hint: "Ask vendors for prices, compare, pick one, then make an order.",
  },
  handover: {
    name: "Give keys",
    hint: "Papers, government certificate, defects, then keys and society.",
  },
  inventory: { name: "Flats and shops", hint: "Which units are free, on hold, booked or sold." },
  "channel desk": {
    name: "Agent daily work",
    hint: "Today’s calls and visits, then hold a unit, then ask to book.",
  },
  "channel firm": {
    name: "Agency office",
    hint: "This company’s agents, holds and commission. You cannot see another company.",
  },
  finance: {
    name: "Company accounts",
    short: "ERPNext",
    hint: "Match Atlas with ERPNext. Atlas never writes a voucher unless posting is on.",
  },
  phases: { name: "All desks", hint: "Only the desks this login is allowed to open." },
  org: {
    name: "People and companies",
    hint: "Who works here and which legal company owns the project.",
  },
  audit: { name: "What changed", hint: "A list of who did what. Rows are not deleted." },
  testing: { name: "Test checklist", hint: "Local tests for the owner. Not for site or sales." },
  decisions: { name: "Owner choices", hint: "Big choices the managing director must record." },
  assistant: { name: "Help draft", hint: "Writes a draft only. It cannot pay, sign or delete." },
  site: {
    name: "Site diary",
    hint: "Today’s work, labour, weather and inspections. Seal once per phone per day.",
  },
  "sales numbers": {
    name: "Sales numbers",
    hint: "How many leads and bookings, and which agents worked.",
  },
  "land papers": {
    name: "Land & acquisition",
    short: "Land papers",
    hint: "Title checks, purchase, and RERA filings for the khasra. The real accounts stay in ERPNext.",
  },
  "land & acquisition": {
    name: "Land & acquisition",
    short: "Land papers",
    hint: "Title checks, purchase, and RERA filings for the khasra. The real accounts stay in ERPNext.",
  },
  ncrs: {
    name: "Failed work still open",
    short: "NCRs",
    hint: "Work that failed inspection and is not closed yet.",
  },
  pass: { name: "Passed", hint: "Inspection found the work is OK." },
  fail: { name: "Failed", hint: "Inspection found a problem. A failed work report is raised." },
  pending: { name: "Waiting", hint: "Someone still has to act." },
  review: { name: "Under check", hint: "A person is checking this before it can move." },
  held: { name: "On hold", hint: "This unit is locked for one buyer for a few days." },
  booked: { name: "Booked", hint: "The buyer has booked this unit. Nobody else can take it." },
  snagging: { name: "Fixing defects", hint: "Defects in the flat are still open." },
  society: { name: "Handed to society", hint: "The building is with the residents’ society." },
  defect: {
    name: "Defect period",
    short: "DLP",
    hint: "After keys, you still fix defects for a set time.",
  },
  quarantine: {
    name: "Virus scan",
    short: "Quarantine",
    hint: "A file-safety hold, not a legal hold. The document is unusable until the scan is cleared.",
  },
  accrued: {
    name: "Earned, not paid",
    hint: "Commission is counted but Atlas does not pay it. A person must approve payment.",
  },
  hot: { name: "Hot lead", hint: "This buyer looks ready. Call them first." },
  warm: { name: "Warm lead", hint: "Some interest. Keep following up." },
  cold: { name: "Cold lead", hint: "Low chance right now." },
  diligence: {
    name: "Land checks",
    hint: "Title, road, conversion and other checks before you buy the land.",
  },
  overdue: { name: "Late", hint: "The due date has passed. File or pay it now." },
  executed: { name: "Work started", hint: "The contract is signed and work or supply can run." },
  reconcil: {
    name: "Matched",
    hint: "Atlas and ERPNext now agree. ERPNext is still the official book.",
  },
};

const ALIAS: Record<string, string> = {
  "change control": "change control",
  "open ncrs": "ncrs",
  ncrs: "ncrs",
  ncr: "ncr",
  rfi: "rfi",
  vo: "vo",
  "variation order": "vo",
  oc: "oc",
  "oc/cc": "oc",
  cc: "cc",
  dlp: "dlp",
  po: "po",
  "purchase order": "po",
  rfq: "rfq",
  ra: "ra",
  "ra bill": "ra",
  grn: "grn",
  kyc: "kyc",
  gstin: "gstin",
  gst: "gstin",
  emi: "emi",
  clu: "clu",
  bocw: "bocw",
  rera: "rera",
  tally: "tally",
  crm: "crm",
  wbs: "wbs",
  bim: "bim",
  sla: "sla",
  command: "command",
  home: "command",
  pipeline: "pipeline",
  inbound: "inbound",
  "customer 360": "customer 360",
  "buyer file": "customer 360",
  controls: "controls",
  commercial: "commercial",
  quotations: "quotations",
  handover: "handover",
  inventory: "inventory",
  "channel desk": "channel desk",
  "channel firm": "channel firm",
  finance: "finance",
  "all phases": "phases",
  phases: "phases",
  organization: "org",
  org: "org",
  audit: "audit",
  "test pack": "testing",
  "owner decisions": "decisions",
  assistant: "assistant",
  snag: "snag",
  snags: "snags",
  hold: "hold",
  held: "held",
  booked: "booked",
  pass: "pass",
  fail: "fail",
  failed: "fail",
  pending: "pending",
  review: "review",
  snagging: "snagging",
  society: "society",
  defect: "defect",
  quarantine: "quarantine",
  accrued: "accrued",
  hot: "hot",
  warm: "warm",
  cold: "cold",
  diligence: "diligence",
  overdue: "overdue",
  executed: "executed",
  reconciled: "reconcil",
  "site questions and quality": "change control",
  "failed work report": "ncr",
  "question to design": "rfi",
  "paid extra work": "vo",
  "give keys": "handover",
  "company accounts": "tally",
  erpnext: "tally",
  "sales partners": "crm",
  "buyer leads": "pipeline",
  "agent daily work": "channel desk",
  "agency office": "channel firm",
  "flats and shops": "inventory",
  "materials and quantities": "controls",
  "vendors and orders": "commercial",
  "price quotes": "quotations",
  "land papers": "land papers",
  "waiting for a yes": "approvals",
  materials: "controls",
  store: "controls",
  "sales numbers": "sales numbers",
  "incoming leads": "inbound",
  "people and companies": "org",
  "all desks": "phases",
  "test checklist": "testing",
  "what changed": "audit",
  "help draft": "assistant",
  "owner choices": "decisions",
  "open items": "owners hub",
  "company money": "capital",
  "site diary": "site",
  quality: "change control",
  today: "channel desk",
  office: "channel firm",
};

export function getTerm(raw: string): GlossaryEntry | undefined {
  const key = raw
    .trim()
    .toLowerCase()
    .replace(/[_./]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  const mapped = ALIAS[key] ?? key;
  return GLOSSARY[mapped] ?? GLOSSARY[key];
}

export function plainName(raw: string) {
  return getTerm(raw)?.name ?? raw.replaceAll("_", " ");
}
