import {
  Building2,
  ClipboardCheck,
  FileStack,
  GitBranch,
  Landmark,
  LayoutDashboard,
  ListChecks,
  Ruler,
  Scale,
  History,
  Map,
  ClipboardList,
  MessageSquare,
  Truck,
  FileSpreadsheet,
  Users,
  Handshake,
  Wallet,
} from "lucide-react";
import type { Role } from "@/lib/types";

export const NAV = [
  { to: "/app", label: "Command", icon: LayoutDashboard, end: true, roles: ["owner", "pm", "engineer", "accountant"] as Role[] },
  { to: "/app/phases", label: "All phases", icon: Map, roles: ["owner", "pm", "engineer", "accountant"] as Role[] },
  { to: "/app/testing", label: "Test pack", icon: ClipboardList, roles: ["owner"] as Role[] },
  { to: "/app/org", label: "Organization", icon: Building2, roles: ["owner", "pm", "accountant"] as Role[] },
  { to: "/app/approvals", label: "Approvals", icon: ListChecks, roles: ["owner", "pm", "accountant"] as Role[] },
  { to: "/app/projects", label: "Projects", icon: Building2, roles: ["owner", "pm", "engineer", "accountant"] as Role[] },
  { to: "/app/documents", label: "Documents", icon: FileStack, roles: ["owner", "pm", "engineer"] as Role[] },
  { to: "/app/land", label: "Land & legal", icon: Landmark, roles: ["owner", "pm", "accountant"] as Role[] },
  { to: "/app/commercial", label: "Commercial", icon: Truck, roles: ["owner", "pm", "accountant"] as Role[] },
  { to: "/app/quotations", label: "Quotations", icon: FileSpreadsheet, roles: ["owner", "pm", "accountant"] as Role[] },
  { to: "/app/site", label: "Site & quality", icon: ClipboardCheck, roles: ["owner", "pm", "engineer"] as Role[] },
  { to: "/app/controls", label: "Controls", icon: Ruler, roles: ["owner", "pm", "engineer"] as Role[] },
  { to: "/app/changes", label: "Change control", icon: GitBranch, roles: ["owner", "pm", "engineer"] as Role[] },
  { to: "/app/customers", label: "Customers", icon: Users, roles: ["owner", "pm", "accountant"] as Role[] },
  { to: "/app/crm", label: "CRM", icon: Handshake, roles: ["owner", "pm", "accountant"] as Role[] },
  { to: "/app/finance", label: "Tally", icon: Scale, roles: ["owner", "accountant"] as Role[] },
  { to: "/app/decisions", label: "Owner decisions", icon: Wallet, roles: ["owner"] as Role[] },
  { to: "/app/audit", label: "Audit", icon: History, roles: ["owner", "pm", "engineer", "accountant"] as Role[] },
  { to: "/app/assistant", label: "Assistant", icon: MessageSquare, roles: ["owner", "pm", "engineer", "accountant"] as Role[] },
];
