import { Badge } from "@/components/ui/badge";

const MAP: Record<string, { tone: "ok" | "warn" | "danger" | "default" | "ink" | "muted"; label?: string }> = {
  active: { tone: "ok" },
  executed: { tone: "ok" },
  issued: { tone: "ok" },
  approved: { tone: "ok" },
  pass: { tone: "ok" },
  reconciled: { tone: "ok" },
  recorded: { tone: "ok" },
  possession: { tone: "ok" },
  construction: { tone: "ok" },
  pending: { tone: "warn" },
  review: { tone: "warn" },
  submitted: { tone: "warn" },
  routed: { tone: "warn" },
  kyc: { tone: "warn" },
  verified: { tone: "warn" },
  bank: { tone: "warn" },
  compliance: { tone: "warn" },
  approval: { tone: "warn" },
  invited: { tone: "muted" },
  draft: { tone: "muted" },
  planning: { tone: "muted" },
  open: { tone: "warn" },
  fail: { tone: "danger" },
  failed: { tone: "danger" },
  rejected: { tone: "danger" },
  critical: { tone: "danger" },
  high: { tone: "danger" },
  quarantine: { tone: "danger" },
  acquired: { tone: "ok" },
  clear: { tone: "ok" },
  filed: { tone: "ok" },
  paid: { tone: "ok" },
  closed: { tone: "ok" },
  exception: { tone: "warn" },
  variance: { tone: "warn" },
  provisional: { tone: "muted" },
  identified: { tone: "muted" },
  diligence: { tone: "warn" },
  overdue: { tone: "danger" },
  flagged: { tone: "danger" },
  used: { tone: "muted" },
  granted: { tone: "ok" },
  inquiry: { tone: "muted" },
  visit: { tone: "warn" },
  negotiation: { tone: "warn" },
  won: { tone: "ok" },
  lost: { tone: "muted" },
  accrued: { tone: "warn" },
  named: { tone: "warn" },
  ready: { tone: "ok" },
  awarded: { tone: "ok" },
  selected: { tone: "ok" },
  cancelled: { tone: "muted" },
  handover: { tone: "ink" },
  restricted: { tone: "ink" },
  confidential: { tone: "warn" },
  hot: { tone: "ok" },
  warm: { tone: "warn" },
  cold: { tone: "muted" },
  available: { tone: "ok" },
  held: { tone: "warn" },
  booked: { tone: "ink" },
  sold: { tone: "ok" },
  dispute: { tone: "danger" },
  documentation: { tone: "warn" },
  snagging: { tone: "warn" },
  society: { tone: "ok" },
  defect: { tone: "warn" },
  scheduled: { tone: "warn" },
  done: { tone: "ok" },
  received: { tone: "ok" },
  expired: { tone: "muted" },
  released: { tone: "muted" },
  queued: { tone: "warn" },
  applied: { tone: "ok" },
  suspended: { tone: "danger" },
  contacted: { tone: "warn" },
  qualified: { tone: "warn" },
  nurture: { tone: "muted" },
  utility: { tone: "ok" },
  marketing: { tone: "warn" },
  paused: { tone: "danger" },
};

export function Status({ value }: { value: string }) {
  const m = MAP[value] ?? { tone: "default" as const };
  return <Badge tone={m.tone}>{m.label ?? value.replaceAll("_", " ")}</Badge>;
}

export const StatusChip = Status;
