import { Hint } from "@/components/hint";
import { Badge } from "@/components/ui/badge";
import { getTerm } from "@/lib/glossary";

const MAP: Record<string, { tone: "ok" | "warn" | "danger" | "default" | "ink" | "muted"; label?: string }> = {
  active: { tone: "ok" },
  executed: { tone: "ok" },
  issued: { tone: "ok" },
  approved: { tone: "ok" },
  pass: { tone: "ok", label: "Passed" },
  reconciled: { tone: "ok" },
  recorded: { tone: "ok" },
  possession: { tone: "ok" },
  construction: { tone: "ok" },
  pending: { tone: "warn", label: "Waiting" },
  review: { tone: "warn", label: "Under check" },
  submitted: { tone: "warn", label: "Sent" },
  kyc: { tone: "warn", label: "Identity check" },
  verified: { tone: "warn" },
  bank: { tone: "warn" },
  compliance: { tone: "warn" },
  approval: { tone: "warn" },
  invited: { tone: "muted" },
  draft: { tone: "muted" },
  planning: { tone: "muted" },
  open: { tone: "warn" },
  fail: { tone: "danger", label: "Failed" },
  failed: { tone: "danger", label: "Failed" },
  rejected: { tone: "danger" },
  critical: { tone: "danger" },
  high: { tone: "danger" },
  quarantine: { tone: "danger", label: "Virus scan" },
  acquired: { tone: "ok" },
  clear: { tone: "ok" },
  filed: { tone: "ok" },
  paid: { tone: "ok" },
  closed: { tone: "ok" },
  exception: { tone: "warn" },
  variance: { tone: "warn", label: "Numbers do not match" },
  provisional: { tone: "muted" },
  identified: { tone: "muted" },
  diligence: { tone: "warn", label: "Land checks" },
  overdue: { tone: "danger", label: "Late" },
  flagged: { tone: "danger" },
  used: { tone: "muted" },
  granted: { tone: "ok" },
  inquiry: { tone: "muted" },
  visit: { tone: "warn" },
  negotiation: { tone: "warn" },
  won: { tone: "ok" },
  lost: { tone: "muted" },
  accrued: { tone: "warn", label: "Earned, not paid" },
  named: { tone: "warn" },
  ready: { tone: "ok" },
  awarded: { tone: "ok" },
  selected: { tone: "ok" },
  cancelled: { tone: "muted" },
  handover: { tone: "ink" },
  restricted: { tone: "ink" },
  confidential: { tone: "warn" },
  hot: { tone: "ok" },
  warm: { tone: "warn" },
  cold: { tone: "muted" },
  available: { tone: "ok" },
  held: { tone: "warn", label: "On hold" },
  booked: { tone: "ink", label: "Booked" },
  sold: { tone: "ok" },
  dispute: { tone: "danger" },
  documentation: { tone: "warn" },
  snagging: { tone: "warn", label: "Fixing defects" },
  society: { tone: "ok", label: "With society" },
  defect: { tone: "warn", label: "Defect period" },
  scheduled: { tone: "warn" },
  done: { tone: "ok" },
  received: { tone: "ok" },
  expired: { tone: "muted" },
  released: { tone: "muted" },
  queued: { tone: "warn" },
  applied: { tone: "ok" },
  suspended: { tone: "danger" },
  contacted: { tone: "warn" },
  qualified: { tone: "warn" },
  nurture: { tone: "muted" },
  utility: { tone: "ok" },
  marketing: { tone: "warn" },
  paused: { tone: "danger" },
  rfi: { tone: "warn", label: "Question to design" },
  ncr: { tone: "danger", label: "Failed work" },
  change: { tone: "warn", label: "Paid extra work" },
  routed: { tone: "warn", label: "Sent to design" },
  corrective: { tone: "warn", label: "Must be fixed" },
};

export function Status({ value }: { value: string }) {
  const m = MAP[value] ?? { tone: "default" as const };
  const g = getTerm(value);
  const label = m.label ?? g?.name ?? value.replaceAll("_", " ");
  const chip = <Badge tone={m.tone}>{label}</Badge>;
  return g ? <Hint term={value}>{chip}</Hint> : chip;
}

export const StatusChip = Status;
