/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppApprovalsRouteImport } from './routes/app/approvals'
import { Route as AppAssistantRouteImport } from './routes/app/assistant'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppChangesRouteImport } from './routes/app/changes'
import { Route as AppCommercialRouteImport } from './routes/app/commercial'
import { Route as AppControlsRouteImport } from './routes/app/controls'
import { Route as AppCrmRouteImport } from './routes/app/crm'
import { Route as AppCustomersRouteImport } from './routes/app/customers'
import { Route as AppDecisionsRouteImport } from './routes/app/decisions'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppFinanceRouteImport } from './routes/app/finance'
import { Route as AppLandRouteImport } from './routes/app/land'
import { Route as AppOrgRouteImport } from './routes/app/org'
import { Route as AppPhasesRouteImport } from './routes/app/phases'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppQuotationsRouteImport } from './routes/app/quotations'
import { Route as AppSiteRouteImport } from './routes/app/site'
import { Route as AppTestingRouteImport } from './routes/app/testing'
import { Route as AppProjectsIdRouteImport } from './routes/app/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)
const AppCommercialRoute = AppCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => AppRoute,
} as any)
const AppControlsRoute = AppControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppLandRoute = AppLandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppPhasesRoute = AppPhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AppRoute,
} as any)
const AppTestingRoute = AppTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/changes': typeof AppChangesRoute
  '/app/commercial': typeof AppCommercialRoute
  '/app/controls': typeof AppControlsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/land': typeof AppLandRoute
  '/app/org': typeof AppOrgRoute
  '/app/phases': typeof AppPhasesRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/quotations': typeof AppQuotationsRoute
  '/app/site': typeof AppSiteRoute
  '/app/testing': typeof AppTestingRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/changes': typeof AppChangesRoute
  '/app/commercial': typeof AppCommercialRoute
  '/app/controls': typeof AppControlsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/land': typeof AppLandRoute
  '/app/org': typeof AppOrgRoute
  '/app/phases': typeof AppPhasesRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/quotations': typeof AppQuotationsRoute
  '/app/site': typeof AppSiteRoute
  '/app/testing': typeof AppTestingRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/changes': typeof AppChangesRoute
  '/app/commercial': typeof AppCommercialRoute
  '/app/controls': typeof AppControlsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/land': typeof AppLandRoute
  '/app/org': typeof AppOrgRoute
  '/app/phases': typeof AppPhasesRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/quotations': typeof AppQuotationsRoute
  '/app/site': typeof AppSiteRoute
  '/app/testing': typeof AppTestingRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/audit'
    | '/app/changes'
    | '/app/commercial'
    | '/app/controls'
    | '/app/crm'
    | '/app/customers'
    | '/app/decisions'
    | '/app/documents'
    | '/app/finance'
    | '/app/land'
    | '/app/org'
    | '/app/phases'
    | '/app/projects'
    | '/app/quotations'
    | '/app/site'
    | '/app/testing'
    | '/app/'
    | '/app/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/audit'
    | '/app/changes'
    | '/app/commercial'
    | '/app/controls'
    | '/app/crm'
    | '/app/customers'
    | '/app/decisions'
    | '/app/documents'
    | '/app/finance'
    | '/app/land'
    | '/app/org'
    | '/app/phases'
    | '/app/projects'
    | '/app/quotations'
    | '/app/site'
    | '/app/testing'
    | '/app'
    | '/app/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/audit'
    | '/app/changes'
    | '/app/commercial'
    | '/app/controls'
    | '/app/crm'
    | '/app/customers'
    | '/app/decisions'
    | '/app/documents'
    | '/app/finance'
    | '/app/land'
    | '/app/org'
    | '/app/phases'
    | '/app/projects'
    | '/app/quotations'
    | '/app/site'
    | '/app/testing'
    | '/app/'
    | '/app/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/changes': {
      id: '/app/changes'
      path: '/changes'
      fullPath: '/app/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commercial': {
      id: '/app/commercial'
      path: '/commercial'
      fullPath: '/app/commercial'
      preLoaderRoute: typeof AppCommercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/controls': {
      id: '/app/controls'
      path: '/controls'
      fullPath: '/app/controls'
      preLoaderRoute: typeof AppControlsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decisions': {
      id: '/app/decisions'
      path: '/decisions'
      fullPath: '/app/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/land': {
      id: '/app/land'
      path: '/land'
      fullPath: '/app/land'
      preLoaderRoute: typeof AppLandRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org': {
      id: '/app/org'
      path: '/org'
      fullPath: '/app/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/phases': {
      id: '/app/phases'
      path: '/phases'
      fullPath: '/app/phases'
      preLoaderRoute: typeof AppPhasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/site': {
      id: '/app/site'
      path: '/site'
      fullPath: '/app/site'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/testing': {
      id: '/app/testing'
      path: '/testing'
      fullPath: '/app/testing'
      preLoaderRoute: typeof AppTestingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppAuditRoute: typeof AppAuditRoute
  AppChangesRoute: typeof AppChangesRoute
  AppCommercialRoute: typeof AppCommercialRoute
  AppControlsRoute: typeof AppControlsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppLandRoute: typeof AppLandRoute
  AppOrgRoute: typeof AppOrgRoute
  AppPhasesRoute: typeof AppPhasesRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppSiteRoute: typeof AppSiteRoute
  AppTestingRoute: typeof AppTestingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppAuditRoute: AppAuditRoute,
  AppChangesRoute: AppChangesRoute,
  AppCommercialRoute: AppCommercialRoute,
  AppControlsRoute: AppControlsRoute,
  AppCrmRoute: AppCrmRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDecisionsRoute: AppDecisionsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppLandRoute: AppLandRoute,
  AppOrgRoute: AppOrgRoute,
  AppPhasesRoute: AppPhasesRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppQuotationsRoute: AppQuotationsRoute,
  AppSiteRoute: AppSiteRoute,
  AppTestingRoute: AppTestingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
